/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PerformanceEvaluation;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author arles96
 */
public class PanelEvaluation extends javax.swing.JPanel {
    
    // Atributes
    
    private Tree tree;
    private final DefaultListModel model = new DefaultListModel();
    private File file;

    // Constructor
    
    public PanelEvaluation() {
        initComponents();
        configurations();
    }
    
    //administration method
    
    private void configurations(){
        addEmployeeList.setModel(model);
        rmEmployeeList.setModel(model);
        addEmployeeLabel.setVisible(false);
    }
    
    private void clearTextField(){
        addTextFieldName.setText("");
        addTextFieldId.setText("");
        addTextFieldValue.setText("");
        addTextFieldArea.setText("");        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addEmployeeList = new javax.swing.JList<>();
        tittleLabel = new javax.swing.JLabel();
        addLabelName = new javax.swing.JLabel();
        addTextFieldName = new javax.swing.JTextField();
        addLabelId = new javax.swing.JLabel();
        addTextFieldId = new javax.swing.JTextField();
        addLabelArea = new javax.swing.JLabel();
        addTextFieldArea = new javax.swing.JTextField();
        addLabelValue = new javax.swing.JLabel();
        addTextFieldValue = new javax.swing.JTextField();
        addEmployee = new javax.swing.JButton();
        openFileButton = new javax.swing.JButton();
        addEmployeeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addLabelName1 = new javax.swing.JLabel();
        rmTextFieldName = new javax.swing.JTextField();
        addLabelArea1 = new javax.swing.JLabel();
        rmTextFieldArea = new javax.swing.JTextField();
        addLabelValue1 = new javax.swing.JLabel();
        rmTextFieldValue = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        rmEmployeeList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeTextArea = new javax.swing.JTextArea();
        tittlePanelLabel = new javax.swing.JLabel();

        setBackground(java.awt.Color.red);

        jPanel1.setBackground(new java.awt.Color(67, 152, 241));

        jScrollPane2.setViewportView(addEmployeeList);

        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("AGREGANDO PERSONAL");

        addLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelName.setText("Nombre");

        addTextFieldName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelId.setText("ID");

        addTextFieldId.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelArea.setText("Area");

        addTextFieldArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelValue.setText("Valor");

        addTextFieldValue.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addEmployee.setText("Agregar");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });

        openFileButton.setText("Abrir Archivo");
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });

        addEmployeeLabel.setText("Seleccione un empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addEmployeeLabel))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(addLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addLabelId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(addLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                            .addComponent(addLabelArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                            .addComponent(addTextFieldArea)
                                            .addComponent(addTextFieldId, javax.swing.GroupLayout.Alignment.TRAILING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(196, 196, 196)
                                .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 284, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                .addComponent(openFileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addEmployeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(134, 134, 134)
                        .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        jPanel2.setBackground(new java.awt.Color(67, 152, 241));

        addLabelName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelName1.setText("Nombre");

        rmTextFieldName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelArea1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelArea1.setText("Area");

        rmTextFieldArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelValue1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelValue1.setText("Valor");

        rmTextFieldValue.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        rmEmployeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                rmEmployeeListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(rmEmployeeList);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificación y Eliminación de Empleados");

        removeButton.setText("Eliminar");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        changeButton.setText("Modificar");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rmTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addLabelValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addLabelArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(changeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rmTextFieldArea)
                                    .addComponent(rmTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))))
                        .addGap(0, 276, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(296, 296, 296)
                    .addComponent(addLabelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(522, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(rmTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rmTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLabelArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rmTextFieldValue)
                            .addComponent(addLabelValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addComponent(addLabelName1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(355, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Modificar y Eliminar", jPanel2);

        treeTextArea.setEditable(false);
        treeTextArea.setColumns(20);
        treeTextArea.setRows(5);
        jScrollPane1.setViewportView(treeTextArea);

        tittlePanelLabel.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        tittlePanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittlePanelLabel.setText("CÁLCULO DE DESEMPEÑO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittlePanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittlePanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane1))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        if (rmEmployeeList.getSelectedIndex()>-1) {
            int number = rmEmployeeList.getSelectedIndex();
            String name, area;
            int value, id;
            name = rmTextFieldName.getText();
            if (name.equals("")) {
                JOptionPane.showMessageDialog(this, "La casilla no posee nombre.");
                return;
            }
            area = rmTextFieldArea.getText();
            if (area.equals("")) {
                JOptionPane.showMessageDialog(this, "La casilla no posee area de trabajo.");
                return;
            }
            try {
                value = Integer.parseInt(rmTextFieldValue.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error en la casilla de valor.");
                return;
            }
            if (value<0) {
                JOptionPane.showMessageDialog(this, "El valor tiene que ser positivo.");
                return;
            }
            tree.changeEmployee(name, area, value,(Employee)model.get(number));
            tree.grades();
            treeTextArea.setText(tree.print());
            rmEmployeeList.repaint();

        }else {
            JOptionPane.showMessageDialog(this, "No se selecciono a ningun empleado.");
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        if (rmEmployeeList.getSelectedIndex()>-1) {
            Employee employee = (Employee) model.get(rmEmployeeList.getSelectedIndex());
            model.remove(rmEmployeeList.getSelectedIndex());
            tree.remove(employee);
            if (tree.getRoot() != null) {
                treeTextArea.setText(tree.print());
            }
            else {
                treeTextArea.setText("");
                rmTextFieldName.setText("");
                rmTextFieldValue.setText("");
                rmTextFieldArea.setText("");
            }
            JOptionPane.showMessageDialog(this, "Se ha eliminado el empleado");
        }
        else {
            JOptionPane.showMessageDialog(this, "No selecciono un empleado");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    private void rmEmployeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_rmEmployeeListValueChanged
        if (rmEmployeeList.getSelectedIndex()>-1) {
            Employee employee = (Employee) model.get(rmEmployeeList.getSelectedIndex());
            rmTextFieldName.setText(employee.getName());
            rmTextFieldArea.setText(employee.getArea());
            rmTextFieldValue.setText("" + employee.getGrade());
        }
    }//GEN-LAST:event_rmEmployeeListValueChanged

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("file", "txt");
        jfc.setFileFilter(filter);
        BufferedReader br;
        FileReader fr;
        int selection  = jfc.showOpenDialog(this);
        ArrayList<String> lines = new ArrayList();
        if (selection == JFileChooser.APPROVE_OPTION) {
            file = jfc.getSelectedFile();
            try {
                fr = new FileReader(file);
                br = new BufferedReader(fr);
                String line;
                while((line=br.readLine())!=null){
                    lines.add(line);
                }
                tree = new Tree(new Employee(Integer.parseInt(""+lines.get(0).charAt(0))));
                model.addElement(tree.getRoot());
                for (int i = 1; i < lines.size(); i++) {
                    String accumulator = "";
                    boolean number1 = true;
                    Employee employee = null;
                    for (int j = 0; j < lines.get(i).length(); j++) {
                        if (lines.get(i).charAt(j)==',') {
                            int number = Integer.parseInt(accumulator);
                            if (number1) {
                                employee = new Employee(number);
                                number1 = false;
                                model.addElement(employee);
                            }else{
                                Employee father = (Employee)model.get(number-1);
                                tree.insertLeaf(father, employee);
                            }
                            accumulator = "";
                        }else {
                            if (lines.get(i).charAt(j)!=' ') {
                                accumulator += lines.get(i).charAt(j);
                            }
                        }
                    }
                    if (employee!=null) {
                        employee.setValue(Integer.parseInt(accumulator));
                    }
                }
                addEmployeeLabel.setVisible(true);
                tree.grades();
                treeTextArea.setText(tree.print());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(this, "Error al abrir el archivo " +
                    file.getName() + ".");
            }
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        String name, area;
        int value, id;
        name = addTextFieldName.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre.");
            return;
        }
        area = addTextFieldArea.getText();
        if (area.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un area de trabajo.");
            return;
        }
        try {
            value = Integer.parseInt(addTextFieldValue.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en la casilla del valor.");
            return;
        }
        if (value<0) {
            JOptionPane.showMessageDialog(this, "El valor tiene que ser positivo.");
            return;
        }
        try {
            id = Integer.parseInt(addTextFieldId.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en la casilla id.");
            return;
        }
        if (tree!=null && !tree.isEmpty() && tree.exists(id)) {
            JOptionPane.showMessageDialog(this, "Ya existe ese id");
            return;
        }
        if (tree==null) {
            tree = new Tree(new Employee(value, name, area, id));
            model.addElement(tree.getRoot());
            addEmployeeLabel.setVisible(true);
        }else {
            if (addEmployeeList.getSelectedIndex()>-1) {
                int number = addEmployeeList.getSelectedIndex();
                Employee boss = (Employee) model.get(number);
                tree.insertLeaf( boss, new Employee(value, name, area, id));
                model.addElement(new Employee(value, name, area, id));
            }
            else {
                JOptionPane.showMessageDialog(this, "No selecciono un empleado");
                return;
            }
        }
        if (tree.getRoot()==null) {
            tree.insertRoot(new Employee(value, name, area, id));
            model.addElement(tree.getRoot());
        }
        tree.grades();
        treeTextArea.setText(tree.print());
        clearTextField();
        JOptionPane.showMessageDialog(this, "Se ha agregado un Empleado.");
    }//GEN-LAST:event_addEmployeeActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployee;
    private javax.swing.JLabel addEmployeeLabel;
    private javax.swing.JList<String> addEmployeeList;
    private javax.swing.JLabel addLabelArea;
    private javax.swing.JLabel addLabelArea1;
    private javax.swing.JLabel addLabelId;
    private javax.swing.JLabel addLabelName;
    private javax.swing.JLabel addLabelName1;
    private javax.swing.JLabel addLabelValue;
    private javax.swing.JLabel addLabelValue1;
    private javax.swing.JTextField addTextFieldArea;
    private javax.swing.JTextField addTextFieldId;
    private javax.swing.JTextField addTextFieldName;
    private javax.swing.JTextField addTextFieldValue;
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JList<String> rmEmployeeList;
    private javax.swing.JTextField rmTextFieldArea;
    private javax.swing.JTextField rmTextFieldName;
    private javax.swing.JTextField rmTextFieldValue;
    private javax.swing.JLabel tittleLabel;
    private javax.swing.JLabel tittlePanelLabel;
    private javax.swing.JTextArea treeTextArea;
    // End of variables declaration//GEN-END:variables
}
