/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PerformanceEvaluation;

import java.awt.HeadlessException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author arles96
 */
public class PanelEvaluation extends javax.swing.JPanel {

    // Constructor
    
    public PanelEvaluation() {
        initComponents();
        configurations();
    }
    
    // Atributes
    
    private Tree tree;
    private final DefaultListModel model = new DefaultListModel();
    
    //administration method
    
    private void configurations(){
        addEmployeeList.setModel(model);
        rmEmployeeList.setModel(model);
        addEmployeeLabel.setVisible(false);
    }
    
    private void clearTextField(){
        addTextFieldName.setText("");
        addTextFieldId.setText("");
        addTextFieldValue.setText("");
        addTextFieldArea.setText("");        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        addEmployeeList = new javax.swing.JList<>();
        tittleLabel = new javax.swing.JLabel();
        addLabelName = new javax.swing.JLabel();
        addTextFieldName = new javax.swing.JTextField();
        addLabelId = new javax.swing.JLabel();
        addTextFieldId = new javax.swing.JTextField();
        addLabelArea = new javax.swing.JLabel();
        addTextFieldArea = new javax.swing.JTextField();
        addLabelValue = new javax.swing.JLabel();
        addTextFieldValue = new javax.swing.JTextField();
        addEmployee = new javax.swing.JButton();
        addEmployeeLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        addLabelName1 = new javax.swing.JLabel();
        rmTextFieldName = new javax.swing.JTextField();
        addLabelId1 = new javax.swing.JLabel();
        rmTextFieldId = new javax.swing.JTextField();
        addLabelArea1 = new javax.swing.JLabel();
        rmTextFieldArea = new javax.swing.JTextField();
        addLabelValue1 = new javax.swing.JLabel();
        rmTextFieldValue = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        rmEmployeeList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeTextArea = new javax.swing.JTextArea();
        tittlePanelLabel = new javax.swing.JLabel();

        jScrollPane2.setViewportView(addEmployeeList);

        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("AGREGANDO PERSONAL");

        addLabelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelName.setText("Nombre");

        addTextFieldName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelId.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelId.setText("ID");

        addTextFieldId.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelArea.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelArea.setText("Area");

        addTextFieldArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelValue.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelValue.setText("Valor");

        addTextFieldValue.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addEmployee.setText("Agregar");
        addEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeActionPerformed(evt);
            }
        });

        addEmployeeLabel.setText("Seleccione un Empleado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(addEmployeeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(addLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(addTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addLabelName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                            .addComponent(addLabelArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(addLabelId, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(addTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                            .addComponent(addTextFieldArea)
                                            .addComponent(addTextFieldId, javax.swing.GroupLayout.Alignment.TRAILING))))))
                        .addGap(0, 301, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addLabelName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLabelId, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addLabelArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addTextFieldValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addLabelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addComponent(addEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addEmployeeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        addLabelName1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelName1.setText("Nombre");

        rmTextFieldName.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelId1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelId1.setText("ID");

        rmTextFieldId.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelArea1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelArea1.setText("Area");

        rmTextFieldArea.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        addLabelValue1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addLabelValue1.setText("Valor");

        rmTextFieldValue.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N

        rmEmployeeList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                rmEmployeeListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(rmEmployeeList);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Modificación y Eliminación de Empleados");

        removeButton.setText("Eliminar");
        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeButtonActionPerformed(evt);
            }
        });

        changeButton.setText("Modificar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 731, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341)
                .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(296, 296, 296)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(addLabelValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(rmTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addLabelName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                                .addComponent(addLabelArea1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addLabelId1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(rmTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                .addComponent(rmTextFieldArea)
                                .addComponent(rmTextFieldId, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap(296, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(142, 142, 142)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addLabelName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rmTextFieldName, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rmTextFieldId, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(addLabelId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(addLabelArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rmTextFieldArea, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rmTextFieldValue, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                        .addComponent(addLabelValue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(157, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Modificar y Eliminar", jPanel2);

        treeTextArea.setEditable(false);
        treeTextArea.setColumns(20);
        treeTextArea.setRows(5);
        jScrollPane1.setViewportView(treeTextArea);

        tittlePanelLabel.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        tittlePanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittlePanelLabel.setText("CÁLCULO DE DESEMPEÑO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tittlePanelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tittlePanelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jTabbedPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeActionPerformed
        String name, area;
        int value, id;
        name = addTextFieldName.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un nombre.");
            return;
        }
        area = addTextFieldArea.getText();
        if (area.equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese un area de trabajo.");
            return;
        }
        try {
            value = Integer.parseInt(addTextFieldValue.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en la casilla del valor.");
            return;
        }
        try {
            id = Integer.parseInt(addTextFieldId.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en la casilla id.");
            return;
        }
        if (tree!=null) {
            if (tree.exists(id)) {
                JOptionPane.showMessageDialog(this, "Ya existe ese id");
                return;
            }
        }
        if (tree==null) {
            tree = new Tree(new Employee(value, name, area, id));
            model.addElement(tree.getRooth());
            addEmployeeLabel.setVisible(true);
        }else {
            if (model.getSize()>0) {
                int number = addEmployeeList.getSelectedIndex();
                Employee boss = (Employee) model.get(number);
                tree.insertLeaf( boss, new Employee(value, name, area, id));
                model.addElement(new Employee(value, name, area, id));
            }
            else {
                return;
            }
        }
        tree.grades();
        treeTextArea.setText(tree.print());
        clearTextField();
        JOptionPane.showMessageDialog(this, "Se ha agregado un Empleado.");
    }//GEN-LAST:event_addEmployeeActionPerformed

    private void rmEmployeeListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_rmEmployeeListValueChanged
        if (model.getSize()>0) {
            Employee employee = (Employee) model.get(rmEmployeeList.getSelectedIndex());
            rmTextFieldName.setText(employee.getName());
            rmTextFieldId.setText(""+employee.getId());
            rmTextFieldArea.setText(employee.getArea());
            rmTextFieldValue.setText("" + employee.getGrade());
        }
    }//GEN-LAST:event_rmEmployeeListValueChanged

    private void removeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeButtonActionPerformed
        try {
           Employee employee = (Employee) model.get(rmEmployeeList.getSelectedIndex());
           model.remove(rmEmployeeList.getSelectedIndex());
           tree.remove(employee);
           treeTextArea.setText(tree.print());
           JOptionPane.showMessageDialog(this, "Se ha eliminado el empleado");
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar.");
        }
    }//GEN-LAST:event_removeButtonActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEmployee;
    private javax.swing.JLabel addEmployeeLabel;
    private javax.swing.JList<String> addEmployeeList;
    private javax.swing.JLabel addLabelArea;
    private javax.swing.JLabel addLabelArea1;
    private javax.swing.JLabel addLabelId;
    private javax.swing.JLabel addLabelId1;
    private javax.swing.JLabel addLabelName;
    private javax.swing.JLabel addLabelName1;
    private javax.swing.JLabel addLabelValue;
    private javax.swing.JLabel addLabelValue1;
    private javax.swing.JTextField addTextFieldArea;
    private javax.swing.JTextField addTextFieldId;
    private javax.swing.JTextField addTextFieldName;
    private javax.swing.JTextField addTextFieldValue;
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton removeButton;
    private javax.swing.JList<String> rmEmployeeList;
    private javax.swing.JTextField rmTextFieldArea;
    private javax.swing.JTextField rmTextFieldId;
    private javax.swing.JTextField rmTextFieldName;
    private javax.swing.JTextField rmTextFieldValue;
    private javax.swing.JLabel tittleLabel;
    private javax.swing.JLabel tittlePanelLabel;
    private javax.swing.JTextArea treeTextArea;
    // End of variables declaration//GEN-END:variables
}
