package math;

/**
 *
 * @author CJ
 */
public class Interfase extends javax.swing.JPanel {

    private int touch = 0;

    /**
     * Creates new form Interfase
     */
    public Interfase() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resolver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        input = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();

        setAutoscrolls(true);
        setName(""); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resolver.setText("Resolver");
        resolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resolverActionPerformed(evt);
            }
        });
        add(resolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Calculador de expresiones matemáticas.");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 20));

        input.setColumns(20);
        input.setLineWrap(true);
        input.setRows(5);
        input.setText(" - Ingrese expresión matemática aquí.");
        input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                inputKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(input);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 590, 70));

        output.setColumns(20);
        output.setLineWrap(true);
        output.setRows(5);
        output.setText(" - Resultado.");
        jScrollPane2.setViewportView(output);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 590, 190));

        anterior.setText("Anterior");
        anterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anteriorMouseClicked(evt);
            }
        });
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        add(anterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, -1));

        siguiente.setText("Siguiente");
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                siguienteMouseClicked(evt);
            }
        });
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 90, -1));

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void resolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resolverActionPerformed
        Math math = new Math(input.getText());
        try {
            math.solve();
            output.setText(math.toString());
            if (!after.isEmpty()) {
                before.push(expression);
            }
            before.push(input.getText());
            after = new Stack();
        } catch (mathException ex) {
            output.setText(ex.getMessage());
        }
        touch = 0;
    }//GEN-LAST:event_resolverActionPerformed

    private void inputKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputKeyTyped
        if (touch == 0) {
            touch++;
            if (evt.getExtendedKeyCode() != 0) {
                input.setText(evt.getKeyChar() + "");
            } else {
                input.setText("");
            }
        }
        if (evt.getKeyChar() == '\n') {
            if (input.getText().length() > 0) {
                input.setText(input.getText().substring(0, input.getText().lastIndexOf("\n"))
                        + input.getText().substring(input.getText().lastIndexOf("\n") + 1, input.getText().length()));
            }
            resolverActionPerformed(null);
        }
    }//GEN-LAST:event_inputKeyTyped

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        if (!before.isEmpty()) {
            expression = (String) before.pull();
            after.push(expression);
            input.setText(expression);
            touch++;
        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        if (!after.isEmpty()) {
            expression = (String) after.pull();
            before.push(expression);
            input.setText(expression);
            touch++;
        }
    }//GEN-LAST:event_siguienteActionPerformed

    private void anteriorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anteriorMouseClicked
        anteriorActionPerformed(null);
    }//GEN-LAST:event_anteriorMouseClicked

    private void siguienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseClicked
        siguienteActionPerformed(null);
    }//GEN-LAST:event_siguienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JTextArea input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea output;
    private javax.swing.JButton resolver;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables
    private Stack before = new Stack();
    private Stack after = new Stack();
    private String expression = "";
}
