/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

/**
 *
 * @author arles96
 */
public class presentation extends javax.swing.JFrame {
    
    //Atributes
    
    private PresentationThread thread;
    private float i=50, j=1;

    //Constructor
    
    public presentation() {
        initComponents();
        configurations();
    }
    
    // administration methods
    
    private void configurations(){
        this.setLocationRelativeTo(null);
        thread = new PresentationThread(progress);
        thread.start();
        thread = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPresentation = new javax.swing.JPanel();
        tittleLabel = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        ImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelPresentation.setBackground(java.awt.Color.black);
        panelPresentation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tittleLabel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        tittleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tittleLabel.setText("ESTRUCTURA DE DATOS I");
        panelPresentation.add(tittleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 460, 30));

        progress.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                progressStateChanged(evt);
            }
        });
        panelPresentation.add(progress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 440, -1));

        ImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/computer-2653375_640.png"))); // NOI18N
        panelPresentation.add(ImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, -1, 493));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPresentation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void progressStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_progressStateChanged
        if (progress.getValue()==i) {
            if (j!=101) {
                this.setOpacity((100-j)/100);
                i++;
                j+=2;
            }
        }
        if (progress.getValue()==100) {
            MainMenu main = new MainMenu();
            main.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_progressStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new presentation().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JPanel panelPresentation;
    private javax.swing.JProgressBar progress;
    private javax.swing.JLabel tittleLabel;
    // End of variables declaration//GEN-END:variables
}
