/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BicolorableGraph;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Dario
 */
public class BicoloreablePanel extends javax.swing.JPanel {

    public BicoloreablePanel() {
        initComponents();
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        panelColores = new javax.swing.JPanel();
        toggleColor1 = new javax.swing.JToggleButton();
        toggleColor2 = new javax.swing.JToggleButton();
        toggleColor3 = new javax.swing.JToggleButton();
        toggleColor4 = new javax.swing.JToggleButton();
        toggleColor5 = new javax.swing.JToggleButton();
        toggleColor6 = new javax.swing.JToggleButton();
        toggleColor7 = new javax.swing.JToggleButton();
        toggleColor8 = new javax.swing.JToggleButton();
        toggleCustom = new javax.swing.JToggleButton();
        panelNodos1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panelNodos = new javax.swing.JPanel();
        toggTerminal = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outText = new javax.swing.JTextArea();
        canvas = new BicolorableGraph.CanvasPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1032, 122));

        panelColores.setBackground(new java.awt.Color(204, 204, 255));
        panelColores.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)), "Paleta de colores"));

        toggleColor1.setBackground(java.awt.Color.red);
        buttonGroup1.add(toggleColor1);
        toggleColor1.setSelected(true);
        toggleColor1.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor1.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor1.setOpaque(true);
        toggleColor1.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor1MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor1);

        toggleColor2.setBackground(java.awt.Color.blue);
        buttonGroup1.add(toggleColor2);
        toggleColor2.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor2.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor2.setOpaque(true);
        toggleColor2.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor2MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor2);

        toggleColor3.setBackground(java.awt.Color.green);
        buttonGroup1.add(toggleColor3);
        toggleColor3.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor3.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor3.setOpaque(true);
        toggleColor3.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor3MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor3);

        toggleColor4.setBackground(java.awt.Color.yellow);
        buttonGroup1.add(toggleColor4);
        toggleColor4.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor4.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor4.setOpaque(true);
        toggleColor4.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor4MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor4);

        toggleColor5.setBackground(java.awt.Color.cyan);
        buttonGroup1.add(toggleColor5);
        toggleColor5.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor5.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor5.setOpaque(true);
        toggleColor5.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor5MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor5);

        toggleColor6.setBackground(java.awt.Color.magenta);
        buttonGroup1.add(toggleColor6);
        toggleColor6.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor6.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor6.setOpaque(true);
        toggleColor6.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor6MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor6);

        toggleColor7.setBackground(java.awt.Color.orange);
        buttonGroup1.add(toggleColor7);
        toggleColor7.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor7.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor7.setOpaque(true);
        toggleColor7.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor7MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor7);

        toggleColor8.setBackground(java.awt.Color.pink);
        buttonGroup1.add(toggleColor8);
        toggleColor8.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleColor8.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleColor8.setOpaque(true);
        toggleColor8.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleColor8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleColor8MouseClicked(evt);
            }
        });
        panelColores.add(toggleColor8);

        toggleCustom.setBackground(java.awt.Color.white);
        buttonGroup1.add(toggleCustom);
        toggleCustom.setToolTipText("Click derecho para elegir un color...");
        toggleCustom.setMaximumSize(new java.awt.Dimension(25, 25));
        toggleCustom.setMinimumSize(new java.awt.Dimension(25, 25));
        toggleCustom.setOpaque(true);
        toggleCustom.setPreferredSize(new java.awt.Dimension(25, 25));
        toggleCustom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleCustomMouseClicked(evt);
            }
        });
        panelColores.add(toggleCustom);

        panelNodos1.setBackground(new java.awt.Color(204, 204, 255));
        panelNodos1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)), "Bicoloreable"));
        panelNodos1.setPreferredSize(new java.awt.Dimension(729, 122));

        jButton1.setText("Limpiar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Bicoloreable");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Kruskal");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Prim");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelNodos1Layout = new javax.swing.GroupLayout(panelNodos1);
        panelNodos1.setLayout(panelNodos1Layout);
        panelNodos1Layout.setHorizontalGroup(
            panelNodos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNodos1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNodos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(panelNodos1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)
                        .addGap(46, 46, 46)
                        .addComponent(jButton4)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        panelNodos1Layout.setVerticalGroup(
            panelNodos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNodos1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(panelNodos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panelNodos.setBackground(new java.awt.Color(204, 204, 255));
        panelNodos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)), "Agregar nodo"));
        panelNodos.setMinimumSize(new java.awt.Dimension(50, 65));
        panelNodos.setPreferredSize(new java.awt.Dimension(50, 65));

        toggTerminal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BicolorableGraph/nodoTerminal.png"))); // NOI18N
        toggTerminal.setToolTipText("Agregar terminal");
        panelNodos.add(toggTerminal);

        outText.setColumns(20);
        outText.setRows(5);
        jScrollPane1.setViewportView(outText);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(panelNodos, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelNodos1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelColores, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelNodos1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );

        add(jPanel1);

        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 851, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        add(canvas);
    }// </editor-fold>//GEN-END:initComponents

    private void toggleColor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor1MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor1MouseClicked

    private void toggleColor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor2MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor2MouseClicked

    private void toggleColor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor3MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor3MouseClicked

    private void toggleColor4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor4MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor4MouseClicked

    private void toggleColor5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor5MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor5MouseClicked

    private void toggleColor6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor6MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor6MouseClicked

    private void toggleColor7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor7MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor7MouseClicked

    private void toggleColor8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColor8MouseClicked
        canvas.applyToSelected(getColorSelection());
        canvas.repaint();
    }//GEN-LAST:event_toggleColor8MouseClicked

    private void toggleCustomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleCustomMouseClicked
        if (evt.getButton() == 1) {
            canvas.applyToSelected(getColorSelection());
        } else if (evt.isMetaDown()) {
            toggleCustom.setBackground(
                JColorChooser.showDialog(this, "Elija el color", toggleCustom.getBackground()));
        }

        canvas.repaint();
    }//GEN-LAST:event_toggleCustomMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        canvas.clean();
    }//GEN-LAST:event_jButton1MouseClicked

    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
        if (toggTerminal.isSelected()) {
            Nodo newNode = new Proceso(String.valueOf(canvas.getDiagrama().size()), evt.getX(), evt.getY(), getColorSelection());
            canvas.addNode(newNode);
        }
        
        canvas.repaint();
    }//GEN-LAST:event_canvasMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Graph graph = CanvasToGraph(false);
        
        System.out.println(graph);
        JOptionPane.showMessageDialog(this, (Bicoloreable.isBicoloreable(graph)));
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Graph graph = CanvasToGraph(true);
        
        outText.setText("");
        printTree(Minimal.Kruskal(graph), "");
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        Graph graph = CanvasToGraph(true);
        
        outText.setText("");
        printTree(Minimal.Prim(graph), "");
    }//GEN-LAST:event_jButton4MouseClicked

    public Graph CanvasToGraph(boolean inf){
        Graph graph = new Graph(canvas.getDiagrama().size(), inf);
        ArrayList<Nodo> nodos = canvas.getDiagrama();
        
        for (Nodo nodo : nodos) {
            if(!nodo.getNextNode().isEmpty()){
                int Start = nodos.indexOf(nodo);
                for (Nodo nodo2 : nodo.getNextNode()) {
                    double val = Math.pow(Math.pow(nodo.getCenterPoint().x - nodo2.getCenterPoint().x, 2) 
                            + Math.pow(nodo.getCenterPoint().y - nodo2.getCenterPoint().y, 2), 0.5);
                    
                    int End = nodos.indexOf(nodo.getNextNode(nodo.getNextNode().indexOf(nodo2)));
                    graph.setNodeConection(Start, End, (int)val);
                }
            }
            graph.setNode(nodo.getText(), nodos.indexOf(nodo));
        }
        
        return graph;
    }
    
    public void printTree(Tree tree, String s){
        outText.setText(outText.getText() + s + tree.getLabel() + " value: " + tree.getValue() + "\n");
        
        if(tree.hasChildren());
        for (int i = 0; i < tree.getChildren().size(); i++) {
            printTree(tree.getChildren().get(i), s + "\t");
        }
    }
    
    public Color getColorSelection() {
        if (toggleColor1.isSelected()) {
            return toggleColor1.getBackground();

        } else if (toggleColor2.isSelected()) {
            return toggleColor2.getBackground();

        } else if (toggleColor3.isSelected()) {
            return toggleColor3.getBackground();

        } else if (toggleColor4.isSelected()) {
            return toggleColor4.getBackground();

        } else if (toggleColor5.isSelected()) {
            return toggleColor5.getBackground();

        } else if (toggleColor6.isSelected()) {
            return toggleColor6.getBackground();

        } else if (toggleColor7.isSelected()) {
            return toggleColor7.getBackground();

        } else if (toggleColor8.isSelected()) {
            return toggleColor8.getBackground();

        } else if (toggleCustom.isSelected()) {
            return toggleCustom.getBackground();

        }
        return Color.WHITE;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private BicolorableGraph.CanvasPanel canvas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea outText;
    private javax.swing.JPanel panelColores;
    private javax.swing.JPanel panelNodos;
    private javax.swing.JPanel panelNodos1;
    private javax.swing.JToggleButton toggTerminal;
    private javax.swing.JToggleButton toggleColor1;
    private javax.swing.JToggleButton toggleColor2;
    private javax.swing.JToggleButton toggleColor3;
    private javax.swing.JToggleButton toggleColor4;
    private javax.swing.JToggleButton toggleColor5;
    private javax.swing.JToggleButton toggleColor6;
    private javax.swing.JToggleButton toggleColor7;
    private javax.swing.JToggleButton toggleColor8;
    private javax.swing.JToggleButton toggleCustom;
    // End of variables declaration//GEN-END:variables
}
